### ISSUE TITLE
ai navigation

### ISSUE THREAD

**Issue by zhaishengfu** [danilw/flat-maze#2]
Hello, I am reading your code but I have one question to ask: Can I integrate Navigation or other AI pathfinding algorithm to your logic??

**Comment by danilw** [comment]
can you join my discord https://discord.gg/JKyqWgt
there I can answer questions like this faster for you and me

**Comment by zhaishengfu** [comment]
the link is dead

**Comment by danilw** [comment]
@zhaishengfu I have answer you in discord
what the problem?
new invite link https://discord.gg/HvWHNp
or write to my PM in discord `danil#0872`

and... he gone
